---

## Based on https://github.com/matrix-org/synapse/blob/master/INSTALL.md#installing-synapse

- name: Install Synapse dependencies
  apt:
    name:
      - build-essential
      - python3-dev
      - libffi-dev
      - python-pip
      - python-setuptools
      - sqlite3
      - libssl-dev
      - python-virtualenv
      - libjpeg-dev
      - libxslt1-dev
    state: present
    update_cache: yes

- name: Upgrade pip and setuptools
  pip:
    name:
      - pip
      - setuptools
      - virtualenv
      - ndg-httpsclient
      - twisted
    state: latest

- name: Create dedicated user for Synapse
  user:
    name: matrix-synapse
    create_home: yes
    home: "{{ synapse_installation_path }}"
    shell: /bin/false
    state: present

- name: Install Synapse using pip
  pip:
    name: matrix-synapse
    chdir: "{{ synapse_installation_path }}"
    virtualenv: "{{ synapse_installation_path }}/env"
    virtualenv_python: python3
    state: present

- name: Check if homeserver config file already exists
  stat:
    path: "{{ synapse_installation_path }}/homeserver.yaml"
  register: config_file

- name: Generate a configuration file
  shell:
    source {{ synapse_installation_path }}/env/bin/activate &&
    python -m synapse.app.homeserver \
      --server-name {{ synapse_server_name }} \
      --config-path homeserver.yaml \
      --generate-config \
      --report-stats={{ synapse_report_stats }}
  args:
    chdir: "{{ synapse_installation_path }}"
    executable: /bin/bash
  when: not config_file.stat.exists

- name: Create custom config folder
  file:
    path: "{{ synapse_installation_path }}/conf.d"
    state: directory
    mode: 0755

- name: Create a system service to run Synapse
  template:
    src: lib/systemd/system/matrix-synapse.service.j2
    dest: /lib/systemd/system/matrix-synapse.service
    mode: 0644
    owner: root
    group: root
  register: service_create

- name: Reload systemctl daemon
  systemd:
    daemon_reload: yes
  when: service_create.changed

- name: Enable matrix-synapse.service
  systemd:
    name: matrix-synapse.service
    enabled: yes

- name: Enable/disable registration for new users
  template:
    src: var/lib/matrix-synapse/conf.d/registration.yaml.j2
    dest: "{{ synapse_installation_path }}/conf.d/registration.yaml"
    mode: 0644
    owner: root
    group: root
  notify: restart matrix-synapse
